package recursion;

/*
*Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples:

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
* */
public class PrintAllSubsequences {
    public static void main(String[] args) {
        String s = "aba";
        printAllSubsequences(s);
    }

    private static void printAllSubsequences(String s) {
        String op = "";
        printAllSubsequences(s, op);
    }

    private static void printAllSubsequences(String s, String op) {
        if (s.length() == 0) {
            System.out.println(op);
            return;
        }
        printAllSubsequences(s.substring(1), op + "");
        printAllSubsequences(s.substring(1), op + s.charAt(0));
    }
}
